### ISSUE TITLE
BTCPay v2 Patch

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/boltz-btcpay-plugin#2]

**Comment by rockstardev** [comment]
This would be super cool - that Boltz plugin is ready for 2.0 release.

**Comment by jackstar12** [comment]
> This would be super cool - that Boltz plugin is ready for 2.0 release.

@rockstardev got the patch ready! We'll have to wait for the builder service to support two major plugin versions at the same time tough.

**Comment by rockstardev** [comment]
@jackstar12 as one doing the coding of plugin builder - would highly advise you to publish critical features on 1.3.x branch and then switch 2.0 version... it's unlikely we'll support major plugin versions at the same time in near future.

**Comment by jackstar12** [comment]
@rockstardev Thats the plan, but whats the point of a 1.x branch if we dont have a way to ship updates to the 1.x users after 2.x has gone live?

**Comment by rockstardev** [comment]
@jackstar12, I was referring to the BTCPay branch. You can maintain your `master` branch on the BTCPay 1.13.x submodule, and then update it to BTCPay 2.0 when ready. However, once you switch to 2.0, you won't be able to provide updates for users on 1.13.x.

I understand this is a challenge, which is why we are considering this issue: [GitHub Issue #28](https://github.com/btcpayserver/btcpayserver-plugin-builder/issues/28). However, it's unlikely that we will have this feature implemented and deployed in the near future.
